# See https://cloud.google.com/cloud-build/docs/build-config

timeout: 1800s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20250513-9264efb079'
    entrypoint: make
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - TAG=$_GIT_TAG
      - PULL_BASE_REF=$_PULL_BASE_REF
      - DOCKER_BUILDKIT=1
    args:
    - release-staging-images
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: 'dev'
  # _PULL_BASE_REF will contain the ref that was pushed to to trigger this build -
  # a branch like 'main' or 'release-0.2', or a tag like 'v0.2'.
  _PULL_BASE_REF: 'dev'
