# permissions for end users to view globalinclusterprefixpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalinclusterprefixpool-viewer-role
rules:
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - globalinclusterprefixpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - globalinclusterprefixpools/status
  verbs:
  - get
