# permissions for end users to view inclusterprefixpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inclusterprefixpool-viewer-role
rules:
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - inclusterprefixpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - inclusterprefixpools/status
  verbs:
  - get
