//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalInClusterIPPool) DeepCopyInto(out *GlobalInClusterIPPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalInClusterIPPool.
func (in *GlobalInClusterIPPool) DeepCopy() *GlobalInClusterIPPool {
	if in == nil {
		return nil
	}
	out := new(GlobalInClusterIPPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalInClusterIPPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalInClusterIPPoolList) DeepCopyInto(out *GlobalInClusterIPPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalInClusterIPPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalInClusterIPPoolList.
func (in *GlobalInClusterIPPoolList) DeepCopy() *GlobalInClusterIPPoolList {
	if in == nil {
		return nil
	}
	out := new(GlobalInClusterIPPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalInClusterIPPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalInClusterPrefixPool) DeepCopyInto(out *GlobalInClusterPrefixPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalInClusterPrefixPool.
func (in *GlobalInClusterPrefixPool) DeepCopy() *GlobalInClusterPrefixPool {
	if in == nil {
		return nil
	}
	out := new(GlobalInClusterPrefixPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalInClusterPrefixPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalInClusterPrefixPoolList) DeepCopyInto(out *GlobalInClusterPrefixPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalInClusterPrefixPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalInClusterPrefixPoolList.
func (in *GlobalInClusterPrefixPoolList) DeepCopy() *GlobalInClusterPrefixPoolList {
	if in == nil {
		return nil
	}
	out := new(GlobalInClusterPrefixPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalInClusterPrefixPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterIPPool) DeepCopyInto(out *InClusterIPPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterIPPool.
func (in *InClusterIPPool) DeepCopy() *InClusterIPPool {
	if in == nil {
		return nil
	}
	out := new(InClusterIPPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InClusterIPPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterIPPoolList) DeepCopyInto(out *InClusterIPPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InClusterIPPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterIPPoolList.
func (in *InClusterIPPoolList) DeepCopy() *InClusterIPPoolList {
	if in == nil {
		return nil
	}
	out := new(InClusterIPPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InClusterIPPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterIPPoolSpec) DeepCopyInto(out *InClusterIPPoolSpec) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedAddresses != nil {
		in, out := &in.ExcludedAddresses, &out.ExcludedAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterIPPoolSpec.
func (in *InClusterIPPoolSpec) DeepCopy() *InClusterIPPoolSpec {
	if in == nil {
		return nil
	}
	out := new(InClusterIPPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterIPPoolStatus) DeepCopyInto(out *InClusterIPPoolStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = new(InClusterIPPoolStatusIPAddresses)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterIPPoolStatus.
func (in *InClusterIPPoolStatus) DeepCopy() *InClusterIPPoolStatus {
	if in == nil {
		return nil
	}
	out := new(InClusterIPPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterIPPoolStatusIPAddresses) DeepCopyInto(out *InClusterIPPoolStatusIPAddresses) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterIPPoolStatusIPAddresses.
func (in *InClusterIPPoolStatusIPAddresses) DeepCopy() *InClusterIPPoolStatusIPAddresses {
	if in == nil {
		return nil
	}
	out := new(InClusterIPPoolStatusIPAddresses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterPrefixPool) DeepCopyInto(out *InClusterPrefixPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterPrefixPool.
func (in *InClusterPrefixPool) DeepCopy() *InClusterPrefixPool {
	if in == nil {
		return nil
	}
	out := new(InClusterPrefixPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InClusterPrefixPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterPrefixPoolList) DeepCopyInto(out *InClusterPrefixPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InClusterPrefixPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterPrefixPoolList.
func (in *InClusterPrefixPoolList) DeepCopy() *InClusterPrefixPoolList {
	if in == nil {
		return nil
	}
	out := new(InClusterPrefixPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InClusterPrefixPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterPrefixPoolSpec) DeepCopyInto(out *InClusterPrefixPoolSpec) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedPrefixes != nil {
		in, out := &in.ExcludedPrefixes, &out.ExcludedPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterPrefixPoolSpec.
func (in *InClusterPrefixPoolSpec) DeepCopy() *InClusterPrefixPoolSpec {
	if in == nil {
		return nil
	}
	out := new(InClusterPrefixPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterPrefixPoolStatus) DeepCopyInto(out *InClusterPrefixPoolStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = new(InClusterPrefixPoolStatusAddresses)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterPrefixPoolStatus.
func (in *InClusterPrefixPoolStatus) DeepCopy() *InClusterPrefixPoolStatus {
	if in == nil {
		return nil
	}
	out := new(InClusterPrefixPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterPrefixPoolStatusAddresses) DeepCopyInto(out *InClusterPrefixPoolStatusAddresses) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterPrefixPoolStatusAddresses.
func (in *InClusterPrefixPoolStatusAddresses) DeepCopy() *InClusterPrefixPoolStatusAddresses {
	if in == nil {
		return nil
	}
	out := new(InClusterPrefixPoolStatusAddresses)
	in.DeepCopyInto(out)
	return out
}
