name: container-image

on:
  push:
    branches:
      - main

jobs:
  main-image:
    name: build "main" image
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      
      - name: Create Licenses Report
        run: |
          make licenses-report
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ghcr.io/telekom/cluster-api-ipam-provider-in-cluster:main
